DROP TABLE restaurants
IF EXISTS;
DROP TABLE dishes
IF EXISTS;
DROP SEQUENCE global_seq
IF EXISTS;

CREATE SEQUENCE GLOBAL_SEQ
  AS INTEGER
  START WITH 100000;

CREATE TABLE restaurants
(
  id          INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  name        VARCHAR(255)            NOT NULL,
  address     VARCHAR(255),
  description VARCHAR(255),
  enabled     BOOLEAN DEFAULT TRUE    NOT NULL
);
CREATE UNIQUE INDEX users_unique_name_idx
  ON restaurants (name);

CREATE TABLE dishes
(
  id            INTEGER GENERATED BY DEFAULT AS SEQUENCE GLOBAL_SEQ PRIMARY KEY,
  rest_id       INTEGER      NOT NULL,
  creation_date TIMESTAMP    NOT NULL,
  name          VARCHAR(255) NOT NULL,
  price         INTEGER      NOT NULL,
  FOREIGN KEY (rest_id) REFERENCES restaurants (id)
    ON DELETE CASCADE
);
CREATE UNIQUE INDEX dishes_unique_date_rest_name_idx
  ON dishes (rest_id, creation_date, name)